name: Deploy to S3 on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'
        
    - name: Test if it works
      run: |
        aws s3 sync strona s3://miecraft/

    - name: Zip Lambda function
      run: |
          ls -la
          cd lambdy
          cd mclambda 
          zip -r function.zip . 
  
    - name: Update Lambda function
      run: |
        aws lambda update-function-code --function-name lambda_function.py --zip-file s3://miecraft/function.zip


        
